"""Derive the JSON Schema of the kept parts from the SDK's beta types.

Usage: anthropic_schema.py SDK SCHEMA

SDK is the folder of the Anthropic Python SDK, at the commit
messages.mtsv cites, that holds types and _types.py; SCHEMA is the
file written.
"""

import ast
import json
import sys
from pathlib import Path

# The kept parts: the beta request's system, tools and messages, and the
# beta response's content, how it ended, and what the API changed in the
# input, each in the class that holds it (messages.mtsv › kept.1,
# schema.1).
REQUEST = ("types/beta/message_create_params.py", "MessageCreateParamsBase")
RESPONSE = ("types/beta/beta_message.py", "BetaMessage")
ROOTS = (
    (*REQUEST, "system"),
    (*REQUEST, "tools"),
    (*REQUEST, "messages"),
    (*RESPONSE, "content"),
    (*RESPONSE, "stop_reason"),
    (*RESPONSE, "stop_sequence"),
    (*RESPONSE, "stop_details"),
    (*RESPONSE, "input_transformations"),
    (*RESPONSE, "context_management"),
)
# A cache control breakpoint is an instruction about delivery, left out
# wherever a type holds it (messages.mtsv › kept.2).
CONTROLS = ("cache_control",)
NOTE = (
    "Generated by python/tools/anthropic_schema.py from the beta types of the"
    " Anthropic Python SDK at the commit messages.mtsv cites; do not edit by hand."
)
# Python's scalar types, and the names of the SDK's own modules outside
# the types folder, as values (PEP 484).
SCALARS = {
    "str": {"type": "string"},
    "int": {"type": "integer"},
    "float": {"type": "number"},
    "bool": {"type": "boolean"},
    "object": {},
    "None": {"type": "null"},
}
ARRAYS = ("Iterable", "List", "Sequence", "SequenceNotStr")
# A file or a path, which the SDK reads before sending: no JSON text
# holds one (RFC 8259, 3. Values; the SDK's _types.py).
NOT_JSON = ("IO", "PathLike")
WRAPPERS = ("Required", "NotRequired")


def main(sdk: str, out: str) -> None:
    folder = Path(sdk)
    modules: dict[str, ast.Module] = {}
    definitions: dict[str, dict] = {}
    places: dict[str, tuple[str, str]] = {}
    queue: list[tuple[str, str]] = []
    properties = {}
    for path, cls, field in ROOTS:
        tree = _module(folder, path, modules)
        annotation = _field(tree, cls, field)
        properties[field] = _schema(annotation, path, (folder, modules, queue))
    while queue:
        path, name = queue.pop(0)
        tree = _module(folder, path, modules)
        key = _key((folder, modules, queue), name, path)
        if key in definitions:
            if places[key] != (path, name):
                raise SystemExit(f"{key} is defined in {places[key][0]} and {path}")
            continue
        places[key] = (path, name)
        definitions[key] = {}
        definitions[key] = _definition(tree, name, path, (folder, modules, queue))
    schema = {"$comment": NOTE, "properties": properties, "definitions": definitions}
    Path(out).write_text(json.dumps(schema, indent=1) + "\n", "utf-8")


def _module(folder: Path, path: str, modules: dict) -> ast.Module:
    if path not in modules:
        modules[path] = ast.parse((folder / path).read_text("utf-8"))
    return modules[path]


def _field(tree: ast.Module, cls: str, field: str) -> ast.expr:
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == cls:
            for item in node.body:
                if isinstance(item, ast.AnnAssign) and item.target.id == field:
                    return item.annotation
    raise SystemExit(f"no field {cls}.{field}")


def _definition(tree: ast.Module, name: str, path: str, context: tuple) -> dict:
    # A named type is a class, a TypedDict or a BaseModel, or an alias;
    # each definition cites the file and the name that define it.
    for node in _statements(tree):
        if isinstance(node, ast.ClassDef) and node.name == name:
            found = _object(node, tree, path, context)
            break
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == name:
            found = _schema(node.value, path, context)
            break
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") == name:
            if isinstance(node.value, ast.Call):
                found = _typed_dict(node.value, path, context)
            else:
                found = _schema(node.value, path, context)
            break
    else:
        raise SystemExit(f"no definition of {name} in {path}")
    return {"$comment": f"{path} › {name}", **found}


def _typed_dict(call: ast.Call, path: str, context: tuple) -> dict:
    # The alternative syntax of a TypedDict: its name, then its keys and
    # their types as a dict, totality as a keyword (PEP 589).
    if getattr(call.func, "id", "") != "TypedDict" or len(call.args) != 2:
        raise SystemExit(f"{path}: no rule for {ast.unparse(call)}")
    total = _total(call.keywords)
    properties: dict[str, dict] = {}
    required: list[str] = []
    for key, annotation in zip(call.args[1].keys, call.args[1].values):
        field = key.value
        if field in CONTROLS:
            continue
        wrapper = _wrapper(annotation)
        if wrapper is not None:
            annotation = annotation.slice
        properties[field] = _schema(annotation, path, context)
        if wrapper == "Required" or (total and wrapper != "NotRequired"):
            required.append(field)
    found: dict = {"type": "object", "properties": properties}
    if required:
        found["required"] = required
    return found


def _total(keywords: list[ast.keyword]) -> bool:
    # A TypedDict is total unless total=False is given (PEP 589).
    return all(
        not (
            k.arg == "total" and isinstance(k.value, ast.Constant) and not k.value.value
        )
        for k in keywords
    )


def _object(node: ast.ClassDef, tree: ast.Module, path: str, context: tuple) -> dict:
    # A TypedDict's keys are required where marked Required, or all
    # where it is total; a BaseModel's fields are required unless they
    # have a default; a class holds the fields of the classes it
    # extends; the object is left open (PEP 589; PEP 655).
    total = _total(node.keywords)
    model = any(getattr(base, "id", "") == "BaseModel" for base in node.bases)
    properties: dict[str, dict] = {}
    required: list[str] = []
    for base in node.bases:
        base_name = getattr(base, "id", "")
        if base_name not in ("TypedDict", "BaseModel") and base_name:
            inherited = _definition(*_locate(base_name, tree, path, context), context)
            properties |= inherited.get("properties", {})
            required += inherited.get("required", [])
    for item in node.body:
        if not isinstance(item, ast.AnnAssign):
            continue
        field = item.target.id
        if field in CONTROLS:
            continue
        annotation = item.annotation
        wrapper = _wrapper(annotation)
        if wrapper is not None:
            annotation = annotation.slice
        if model:
            needed = item.value is None
        else:
            needed = wrapper == "Required" or (total and wrapper != "NotRequired")
        properties[field] = _schema(annotation, path, context)
        if needed:
            required.append(field)
    found: dict = {"type": "object", "properties": properties}
    if required:
        found["required"] = required
    return found


def _wrapper(annotation: ast.expr) -> str | None:
    if isinstance(annotation, ast.Subscript):
        name = getattr(annotation.value, "id", "")
        if name in WRAPPERS:
            return name
    return None


def _schema(node: ast.expr, path: str, context: tuple) -> dict | None:
    # Union for alternatives, Optional for or null, Literal for fixed
    # values, an iterable for an array, Dict[str, X] for an object of X,
    # and a named type for its definition; None for what no JSON text
    # holds (PEP 484; PEP 586).
    if isinstance(node, ast.Constant) and node.value is None:
        return SCALARS["None"]
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return _schema(ast.parse(node.value, mode="eval").body, path, context)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
        return {
            "anyOf": [_schema(side, path, context) for side in (node.left, node.right)]
        }
    if isinstance(node, ast.Name):
        if node.id in NOT_JSON:
            return None
        if node.id in SCALARS:
            return SCALARS[node.id]
        if node.id in ARRAYS:
            return {"type": "array"}
        if node.id == "Dict":
            return {"type": "object"}
        tree, name, target = _locate(node.id, context[1][path], path, context)
        if _no_json(tree, name, target, context):
            return None
        context[2].append((target, name))
        return {"$ref": f"#/definitions/{_key(context, name, target)}"}
    if isinstance(node, ast.Subscript):
        outer = getattr(node.value, "id", "")
        inner = node.slice.elts if isinstance(node.slice, ast.Tuple) else [node.slice]
        if outer in NOT_JSON:
            return None
        if outer == "Union":
            kept = [_schema(each, path, context) for each in inner]
            kept = [each for each in kept if each is not None]
            return {"anyOf": kept} if kept else None
        if outer == "Optional":
            return {"anyOf": [_schema(inner[0], path, context), SCALARS["None"]]}
        if outer == "Literal":
            values = [each.value for each in inner]
            kinds = {type(v).__name__ for v in values}
            typed = {"str": "string", "int": "integer", "bool": "boolean"}
            found: dict = {"enum": values}
            if len(kinds) == 1 and kinds <= set(typed):
                found = {"type": typed[kinds.pop()], "enum": values}
            return found
        if outer in ARRAYS:
            return {"type": "array", "items": _schema(inner[0], path, context)}
        if outer == "Dict":
            values = _schema(inner[1], path, context)
            return {
                "type": "object",
                **({"additionalProperties": values} if values else {}),
            }
        if outer in WRAPPERS or outer == "Annotated":
            return _schema(inner[0], path, context)
    raise SystemExit(f"{path}: no rule for {ast.unparse(node)}")


def _no_json(tree: ast.Module, name: str, path: str, context: tuple) -> bool:
    # An alias of alternatives none of which a JSON text can hold.
    for node in _statements(tree):
        if isinstance(node, (ast.Assign, ast.AnnAssign)) and not isinstance(
            node.value, ast.Call
        ):
            target = node.targets[0] if isinstance(node, ast.Assign) else node.target
            if getattr(target, "id", "") == name:
                trial = (context[0], context[1], [])
                return _schema(node.value, path, trial) is None
    return False


def _statements(tree: ast.Module) -> list[ast.stmt]:
    # A module's statements, and those a type checker reads under if
    # TYPE_CHECKING (PEP 484, Runtime or type checking?).
    found = []
    for node in tree.body:
        if isinstance(node, ast.If) and getattr(node.test, "id", "") == "TYPE_CHECKING":
            found += node.body
        else:
            found.append(node)
    return found


def _key(context: tuple, name: str, path: str) -> str:
    # A type its package exports is named by its name; any other by its
    # module's name, '.', and its name, since two modules may hold types
    # of one name (messages.mtsv › schema.7).
    package_path = (Path(path).parent / "__init__.py").as_posix()
    package = _module(context[0], package_path, context[1])
    exported = {
        alias.asname or alias.name
        for node in package.body
        if isinstance(node, ast.ImportFrom)
        for alias in node.names
    }
    return name if name in exported else f"{Path(path).stem}.{name}"


def _locate(name: str, tree: ast.Module, path: str, context: tuple) -> tuple:
    # A name is defined in its module, or imported from the module that
    # defines it, a relative import counted from the importing module's
    # folder.
    for node in _statements(tree):
        defined = (
            (isinstance(node, ast.ClassDef) and node.name == name)
            or (
                isinstance(node, ast.AnnAssign)
                and getattr(node.target, "id", "") == name
            )
            or (
                isinstance(node, ast.Assign)
                and getattr(node.targets[0], "id", "") == name
            )
        )
        if defined:
            return tree, name, path
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.level and node.module:
            if any(alias.name == name and alias.asname is None for alias in node.names):
                parts = list(Path(path).parent.parts)
                up = node.level - 1
                if up > len(parts):
                    raise SystemExit(f"{path}: {name} is outside the SDK folder")
                kept = parts[: len(parts) - up]
                target = "/".join([*kept, *node.module.split(".")]) + ".py"
                target_tree = _module(context[0], target, context[1])
                return _locate(name, target_tree, target, context)
    raise SystemExit(f"{path}: {name} is neither defined nor imported")


if __name__ == "__main__":
    main(*sys.argv[1:])
